CREATE TABLE IF NOT EXISTS IDK(
    NAME TEXT,
    NEIGHBOUR TEXT,
    CUSINE TEXT,
    REVIEW REAL,
    PRICE TEXT,
    HEALTH TEXT
);
INSERT INTO IDK(NAME,NEIGHBOUR,CUSINE,REVIEW,PRICE,HEALTH)
VALUES  
    ('PETER','BROOK','STEAK',4.4,'$','A'),
    ('JOHN','MIDTOWN','KOREAN',3.5,'$$','A'),
    ('POCHA','SQUEENS','PIZZA',4,'$$$$','B'),
    ('JOE','ROOT','BURGER',5,'$$','A'),
    ('CHRIS','WOOD','ITALIAN',4.1,'$$','');

SELECT * FROM IDK;

SELECT DISTINCT NEIGHBOUR FROM IDK;

SELECT DISTINCT CUSINE FROM IDK;
SELECT * FROM IDK WHERE CUSINE = 'ITALIAN';

SELECT * FROM IDK WHERE LIKE 'JOE' ;

SELECT * FROM IDK WHERE REVIEW >=4;

SELECT * FROM IDK WHERE CUSINE = 'PIZZA' AND PRICE = '$$$$';

SELECT * FROM IDK 
WHERE NEIGHBOUR IN ('MIDTOWN','ROOT','WOOD');

SELECT * FROM IDK ORDER BY REVIEW DESC LIMIT 4;

